// Generated by Projects/Documents/Drafts/Andrew Meal Plan (generator).py. Do not edit by hand.
window.PLAN = {
 "targets": {
  "A": {
   "label": "Non-drinking day",
   "kcal": [
    1950,
    2050
   ],
   "protein": [
    175,
    185
   ],
   "carbs": [
    135,
    155
   ],
   "fat": [
    65,
    75
   ]
  },
  "B": {
   "label": "Drinking day",
   "kcal": [
    1700,
    1800
   ],
   "protein": [
    175,
    185
   ],
   "carbs": [
    110,
    140
   ],
   "fat": [
    48,
    60
   ]
  }
 },
 "drinks": {
  "name": "Meister Max 500 ml, 8%",
  "cans": 3,
  "kcalPerCan": 269,
  "carbsPerCan": 12
 },
 "days": [
  {
   "day": "Monday",
   "training": "Gym, evening",
   "shape": "Heavy dinner, no supper",
   "options": {
    "A": [
     {
      "time": "08:30",
      "name": "Breakfast",
      "note": "Scrambled eggs with turkey, toast, salad in the oil",
      "items": [
       {
        "id": "mon-A-0-0",
        "label": "3 large eggs",
        "kcal": 216,
        "protein": 18.9,
        "carbs": 1.2,
        "fat": 14.4
       },
       {
        "id": "mon-A-0-1",
        "label": "2 slices bran toast",
        "kcal": 110,
        "protein": 4.4,
        "carbs": 19.6,
        "fat": 1.2
       },
       {
        "id": "mon-A-0-2",
        "label": "2 slices smoked turkey",
        "kcal": 50,
        "protein": 9.0,
        "carbs": 1.0,
        "fat": 1.0
       },
       {
        "id": "mon-A-0-3",
        "label": "100 g salad veg (cucumber, tomato, leaves)",
        "kcal": 20,
        "protein": 1.0,
        "carbs": 3.5,
        "fat": 0.2
       },
       {
        "id": "mon-A-0-4",
        "label": "2 tsp olive oil",
        "kcal": 88,
        "protein": 0.0,
        "carbs": 0.0,
        "fat": 10.0
       }
      ]
     },
     {
      "time": "13:30",
      "name": "Lunch",
      "note": "Grilled chicken, rice, steamed veg with the oil over it",
      "items": [
       {
        "id": "mon-A-1-0",
        "label": "150 g chicken breast (cooked)",
        "kcal": 248,
        "protein": 46.5,
        "carbs": 0.0,
        "fat": 5.4
       },
       {
        "id": "mon-A-1-1",
        "label": "220 g basmati rice, cooked (80 g dry)",
        "kcal": 286,
        "protein": 5.9,
        "carbs": 61.6,
        "fat": 0.7
       },
       {
        "id": "mon-A-1-2",
        "label": "200 g steamed mixed veg",
        "kcal": 70,
        "protein": 4.0,
        "carbs": 12.0,
        "fat": 0.6
       },
       {
        "id": "mon-A-1-3",
        "label": "1 tsp olive oil",
        "kcal": 44,
        "protein": 0.0,
        "carbs": 0.0,
        "fat": 5.0
       }
      ]
     },
     {
      "time": "20:45",
      "name": "After the gym",
      "note": "Shake with water, banana on the side",
      "items": [
       {
        "id": "mon-A-2-0",
        "label": "1 scoop whey protein (30 g) in water",
        "kcal": 120,
        "protein": 24.0,
        "carbs": 3.0,
        "fat": 2.0
       },
       {
        "id": "mon-A-2-1",
        "label": "1 medium banana",
        "kcal": 105,
        "protein": 1.3,
        "carbs": 27.0,
        "fat": 0.4
       },
       {
        "id": "mon-A-2-2",
        "label": "1 tsp honey",
        "kcal": 21,
        "protein": 0.0,
        "carbs": 5.7,
        "fat": 0.0
       }
      ]
     },
     {
      "time": "21:30",
      "name": "Dinner",
      "note": "Pan-seared fillet, veg in the oil",
      "items": [
       {
        "id": "mon-A-3-0",
        "label": "220 g beef fillet (cooked)",
        "kcal": 407,
        "protein": 60.5,
        "carbs": 0.0,
        "fat": 17.6
       },
       {
        "id": "mon-A-3-1",
        "label": "250 g steamed mixed veg",
        "kcal": 88,
        "protein": 5.0,
        "carbs": 15.0,
        "fat": 0.8
       },
       {
        "id": "mon-A-3-2",
        "label": "2 tsp olive oil",
        "kcal": 88,
        "protein": 0.0,
        "carbs": 0.0,
        "fat": 10.0
       }
      ]
     }
    ],
    "B": [
     {
      "time": "08:30",
      "name": "Breakfast",
      "note": "Scrambled eggs with cheddar melted in, toast, salad",
      "items": [
       {
        "id": "mon-B-0-0",
        "label": "3 large eggs",
        "kcal": 216,
        "protein": 18.9,
        "carbs": 1.2,
        "fat": 14.4
       },
       {
        "id": "mon-B-0-1",
        "label": "2 slices bran toast",
        "kcal": 110,
        "protein": 4.4,
        "carbs": 19.6,
        "fat": 1.2
       },
       {
        "id": "mon-B-0-2",
        "label": "100 g salad veg (cucumber, tomato, leaves)",
        "kcal": 20,
        "protein": 1.0,
        "carbs": 3.5,
        "fat": 0.2
       },
       {
        "id": "mon-B-0-3",
        "label": "1 slice cheddar",
        "kcal": 82,
        "protein": 5.0,
        "carbs": 0.2,
        "fat": 6.8
       }
      ]
     },
     {
      "time": "13:30",
      "name": "Lunch",
      "note": "Grilled chicken, steamed veg, no rice or oil today. The wrap tonight is the carbs",
      "items": [
       {
        "id": "mon-B-1-0",
        "label": "150 g chicken breast (cooked)",
        "kcal": 248,
        "protein": 46.5,
        "carbs": 0.0,
        "fat": 5.4
       },
       {
        "id": "mon-B-1-1",
        "label": "250 g steamed mixed veg",
        "kcal": 88,
        "protein": 5.0,
        "carbs": 15.0,
        "fat": 0.8
       }
      ]
     },
     {
      "time": "20:45",
      "name": "After the gym",
      "note": "Shake with water",
      "items": [
       {
        "id": "mon-B-2-0",
        "label": "1 scoop whey protein (30 g) in water",
        "kcal": 120,
        "protein": 24.0,
        "carbs": 3.0,
        "fat": 2.0
       }
      ]
     },
     {
      "time": "21:30",
      "name": "Dinner, before the drinks",
      "note": "Tuna and veg wrap. Eat this before the first can",
      "items": [
       {
        "id": "mon-B-3-0",
        "label": "150 g tuna in water (drained)",
        "kcal": 174,
        "protein": 39.0,
        "carbs": 0.0,
        "fat": 1.5
       },
       {
        "id": "mon-B-3-1",
        "label": "200 g steamed mixed veg",
        "kcal": 70,
        "protein": 4.0,
        "carbs": 12.0,
        "fat": 0.6
       },
       {
        "id": "mon-B-3-2",
        "label": "1 tsp olive oil",
        "kcal": 44,
        "protein": 0.0,
        "carbs": 0.0,
        "fat": 5.0
       },
       {
        "id": "mon-B-3-3",
        "label": "1 large bran tortilla (90 g)",
        "kcal": 250,
        "protein": 7.0,
        "carbs": 53.0,
        "fat": 1.0
       }
      ]
     },
     {
      "time": "After drinks",
      "name": "Supper",
      "note": "Cottage cheese on toast, then bed",
      "items": [
       {
        "id": "mon-B-4-0",
        "label": "200 g cottage cheese",
        "kcal": 196,
        "protein": 22.0,
        "carbs": 6.8,
        "fat": 8.6
       },
       {
        "id": "mon-B-4-1",
        "label": "2 slices bran toast",
        "kcal": 110,
        "protein": 4.4,
        "carbs": 19.6,
        "fat": 1.2
       }
      ]
     }
    ]
   }
  },
  {
   "day": "Tuesday",
   "training": "Padel, evening",
   "shape": "Light dinner, supper",
   "options": {
    "A": [
     {
      "time": "09:00",
      "name": "Breakfast",
      "note": "Yogurt cup, bread snack, one boiled egg. Quick one",
      "items": [
       {
        "id": "tue-A-0-0",
        "label": "1 HiPro strawberry Greek yogurt cup (200 g)",
        "kcal": 150,
        "protein": 25.0,
        "carbs": 10.0,
        "fat": 2.0
       },
       {
        "id": "tue-A-0-1",
        "label": "30 g Balance bread snack",
        "kcal": 120,
        "protein": 6.6,
        "carbs": 20.5,
        "fat": 1.3
       },
       {
        "id": "tue-A-0-2",
        "label": "1 large egg",
        "kcal": 72,
        "protein": 6.3,
        "carbs": 0.4,
        "fat": 4.8
       }
      ]
     },
     {
      "time": "13:30",
      "name": "Lunch",
      "note": "Mince cooked with onion and spices, rice, veg",
      "items": [
       {
        "id": "tue-A-1-0",
        "label": "190 g 5% minced beef (cooked)",
        "kcal": 314,
        "protein": 51.3,
        "carbs": 0.0,
        "fat": 12.3
       },
       {
        "id": "tue-A-1-1",
        "label": "200 g steamed mixed veg",
        "kcal": 70,
        "protein": 4.0,
        "carbs": 12.0,
        "fat": 0.6
       },
       {
        "id": "tue-A-1-2",
        "label": "220 g basmati rice, cooked (80 g dry)",
        "kcal": 286,
        "protein": 5.9,
        "carbs": 61.6,
        "fat": 0.7
       },
       {
        "id": "tue-A-1-3",
        "label": "1 tsp olive oil",
        "kcal": 44,
        "protein": 0.0,
        "carbs": 0.0,
        "fat": 5.0
       }
      ]
     },
     {
      "time": "21:00",
      "name": "Dinner, after padel",
      "note": "Turkey and cheddar omelette, salad in the oil",
      "items": [
       {
        "id": "tue-A-2-0",
        "label": "4 large eggs",
        "kcal": 288,
        "protein": 25.2,
        "carbs": 1.6,
        "fat": 19.2
       },
       {
        "id": "tue-A-2-1",
        "label": "4 slices smoked turkey",
        "kcal": 100,
        "protein": 18.0,
        "carbs": 2.0,
        "fat": 2.0
       },
       {
        "id": "tue-A-2-2",
        "label": "1 slice cheddar",
        "kcal": 82,
        "protein": 5.0,
        "carbs": 0.2,
        "fat": 6.8
       },
       {
        "id": "tue-A-2-3",
        "label": "150 g salad veg (cucumber, tomato, leaves)",
        "kcal": 30,
        "protein": 1.5,
        "carbs": 5.2,
        "fat": 0.3
       },
       {
        "id": "tue-A-2-4",
        "label": "1 tsp olive oil",
        "kcal": 44,
        "protein": 0.0,
        "carbs": 0.0,
        "fat": 5.0
       }
      ]
     },
     {
      "time": "23:00",
      "name": "Supper",
      "note": "Cottage cheese on toast, black pepper",
      "items": [
       {
        "id": "tue-A-3-0",
        "label": "250 g cottage cheese",
        "kcal": 245,
        "protein": 27.5,
        "carbs": 8.5,
        "fat": 10.8
       },
       {
        "id": "tue-A-3-1",
        "label": "2 slices bran toast",
        "kcal": 110,
        "protein": 4.4,
        "carbs": 19.6,
        "fat": 1.2
       }
      ]
     }
    ],
    "B": [
     {
      "time": "09:00",
      "name": "Breakfast",
      "note": "Yogurt cup, bread snack, two boiled eggs",
      "items": [
       {
        "id": "tue-B-0-0",
        "label": "1 HiPro strawberry Greek yogurt cup (200 g)",
        "kcal": 150,
        "protein": 25.0,
        "carbs": 10.0,
        "fat": 2.0
       },
       {
        "id": "tue-B-0-1",
        "label": "30 g Balance bread snack",
        "kcal": 120,
        "protein": 6.6,
        "carbs": 20.5,
        "fat": 1.3
       },
       {
        "id": "tue-B-0-2",
        "label": "2 large eggs",
        "kcal": 144,
        "protein": 12.6,
        "carbs": 0.8,
        "fat": 9.6
       }
      ]
     },
     {
      "time": "13:30",
      "name": "Lunch",
      "note": "Mince with onion and spices, veg, no rice today. The wrap tonight is the carbs",
      "items": [
       {
        "id": "tue-B-1-0",
        "label": "150 g 5% minced beef (cooked)",
        "kcal": 248,
        "protein": 40.5,
        "carbs": 0.0,
        "fat": 9.8
       },
       {
        "id": "tue-B-1-1",
        "label": "200 g steamed mixed veg",
        "kcal": 70,
        "protein": 4.0,
        "carbs": 12.0,
        "fat": 0.6
       },
       {
        "id": "tue-B-1-2",
        "label": "1 tsp olive oil",
        "kcal": 44,
        "protein": 0.0,
        "carbs": 0.0,
        "fat": 5.0
       }
      ]
     },
     {
      "time": "21:00",
      "name": "Dinner, before the drinks",
      "note": "Chicken and veg wrap. Eat before the first can",
      "items": [
       {
        "id": "tue-B-2-0",
        "label": "150 g chicken breast (cooked)",
        "kcal": 248,
        "protein": 46.5,
        "carbs": 0.0,
        "fat": 5.4
       },
       {
        "id": "tue-B-2-1",
        "label": "250 g steamed mixed veg",
        "kcal": 88,
        "protein": 5.0,
        "carbs": 15.0,
        "fat": 0.8
       },
       {
        "id": "tue-B-2-2",
        "label": "1 tsp olive oil",
        "kcal": 44,
        "protein": 0.0,
        "carbs": 0.0,
        "fat": 5.0
       },
       {
        "id": "tue-B-2-3",
        "label": "1 large bran tortilla (90 g)",
        "kcal": 250,
        "protein": 7.0,
        "carbs": 53.0,
        "fat": 1.0
       }
      ]
     },
     {
      "time": "After drinks",
      "name": "Supper",
      "note": "Cottage cheese and turkey on toast, then bed",
      "items": [
       {
        "id": "tue-B-3-0",
        "label": "200 g cottage cheese",
        "kcal": 196,
        "protein": 22.0,
        "carbs": 6.8,
        "fat": 8.6
       },
       {
        "id": "tue-B-3-1",
        "label": "2 slices bran toast",
        "kcal": 110,
        "protein": 4.4,
        "carbs": 19.6,
        "fat": 1.2
       },
       {
        "id": "tue-B-3-2",
        "label": "2 slices smoked turkey",
        "kcal": 50,
        "protein": 9.0,
        "carbs": 1.0,
        "fat": 1.0
       }
      ]
     }
    ]
   }
  },
  {
   "day": "Wednesday",
   "training": "Gym, evening",
   "shape": "Heavy dinner, no supper",
   "options": {
    "A": [
     {
      "time": "08:30",
      "name": "Breakfast",
      "note": "Cottage cheese on toast, two boiled eggs, turkey, tomato and cucumber",
      "items": [
       {
        "id": "wed-A-0-0",
        "label": "200 g cottage cheese",
        "kcal": 196,
        "protein": 22.0,
        "carbs": 6.8,
        "fat": 8.6
       },
       {
        "id": "wed-A-0-1",
        "label": "2 slices bran toast",
        "kcal": 110,
        "protein": 4.4,
        "carbs": 19.6,
        "fat": 1.2
       },
       {
        "id": "wed-A-0-2",
        "label": "2 large eggs",
        "kcal": 144,
        "protein": 12.6,
        "carbs": 0.8,
        "fat": 9.6
       },
       {
        "id": "wed-A-0-3",
        "label": "1 slice smoked turkey",
        "kcal": 25,
        "protein": 4.5,
        "carbs": 0.5,
        "fat": 0.5
       },
       {
        "id": "wed-A-0-4",
        "label": "100 g salad veg (cucumber, tomato, leaves)",
        "kcal": 20,
        "protein": 1.0,
        "carbs": 3.5,
        "fat": 0.2
       }
      ]
     },
     {
      "time": "13:30",
      "name": "Lunch",
      "note": "One big tuna wrap with salad in the oil. Tuna in oil, drained",
      "items": [
       {
        "id": "wed-A-1-0",
        "label": "130 g tuna in sunflower oil (drained)",
        "kcal": 247,
        "protein": 32.5,
        "carbs": 0.0,
        "fat": 13.0
       },
       {
        "id": "wed-A-1-1",
        "label": "1 large bran tortilla (90 g)",
        "kcal": 250,
        "protein": 7.0,
        "carbs": 53.0,
        "fat": 1.0
       },
       {
        "id": "wed-A-1-2",
        "label": "150 g salad veg (cucumber, tomato, leaves)",
        "kcal": 30,
        "protein": 1.5,
        "carbs": 5.2,
        "fat": 0.3
       },
       {
        "id": "wed-A-1-3",
        "label": "2 tsp olive oil",
        "kcal": 88,
        "protein": 0.0,
        "carbs": 0.0,
        "fat": 10.0
       }
      ]
     },
     {
      "time": "20:45",
      "name": "After the gym",
      "note": "Shake with water, banana on the side",
      "items": [
       {
        "id": "wed-A-2-0",
        "label": "1 scoop whey protein (30 g) in water",
        "kcal": 120,
        "protein": 24.0,
        "carbs": 3.0,
        "fat": 2.0
       },
       {
        "id": "wed-A-2-1",
        "label": "1 medium banana",
        "kcal": 105,
        "protein": 1.3,
        "carbs": 27.0,
        "fat": 0.4
       }
      ]
     },
     {
      "time": "21:30",
      "name": "Dinner",
      "note": "Grilled chicken, a small spoon of rice, veg in the oil",
      "items": [
       {
        "id": "wed-A-3-0",
        "label": "200 g chicken breast (cooked)",
        "kcal": 330,
        "protein": 62.0,
        "carbs": 0.0,
        "fat": 7.2
       },
       {
        "id": "wed-A-3-1",
        "label": "250 g steamed mixed veg",
        "kcal": 88,
        "protein": 5.0,
        "carbs": 15.0,
        "fat": 0.8
       },
       {
        "id": "wed-A-3-2",
        "label": "60 g basmati rice, cooked (20 g dry)",
        "kcal": 78,
        "protein": 1.6,
        "carbs": 16.8,
        "fat": 0.2
       },
       {
        "id": "wed-A-3-3",
        "label": "3 tsp olive oil",
        "kcal": 132,
        "protein": 0.0,
        "carbs": 0.0,
        "fat": 15.0
       }
      ]
     }
    ],
    "B": [
     {
      "time": "08:30",
      "name": "Breakfast",
      "note": "Cottage cheese on toast, turkey on top, tomato and cucumber",
      "items": [
       {
        "id": "wed-B-0-0",
        "label": "200 g cottage cheese",
        "kcal": 196,
        "protein": 22.0,
        "carbs": 6.8,
        "fat": 8.6
       },
       {
        "id": "wed-B-0-1",
        "label": "2 slices bran toast",
        "kcal": 110,
        "protein": 4.4,
        "carbs": 19.6,
        "fat": 1.2
       },
       {
        "id": "wed-B-0-2",
        "label": "2 slices smoked turkey",
        "kcal": 50,
        "protein": 9.0,
        "carbs": 1.0,
        "fat": 1.0
       },
       {
        "id": "wed-B-0-3",
        "label": "100 g salad veg (cucumber, tomato, leaves)",
        "kcal": 20,
        "protein": 1.0,
        "carbs": 3.5,
        "fat": 0.2
       }
      ]
     },
     {
      "time": "13:30",
      "name": "Lunch",
      "note": "One tuna wrap with salad in the oil. Tuna in water today",
      "items": [
       {
        "id": "wed-B-1-0",
        "label": "120 g tuna in water (drained)",
        "kcal": 139,
        "protein": 31.2,
        "carbs": 0.0,
        "fat": 1.2
       },
       {
        "id": "wed-B-1-1",
        "label": "1 large bran tortilla (90 g)",
        "kcal": 250,
        "protein": 7.0,
        "carbs": 53.0,
        "fat": 1.0
       },
       {
        "id": "wed-B-1-2",
        "label": "150 g salad veg (cucumber, tomato, leaves)",
        "kcal": 30,
        "protein": 1.5,
        "carbs": 5.2,
        "fat": 0.3
       },
       {
        "id": "wed-B-1-3",
        "label": "3 tsp olive oil",
        "kcal": 132,
        "protein": 0.0,
        "carbs": 0.0,
        "fat": 15.0
       }
      ]
     },
     {
      "time": "20:45",
      "name": "After the gym",
      "note": "Shake with water",
      "items": [
       {
        "id": "wed-B-2-0",
        "label": "1 scoop whey protein (30 g) in water",
        "kcal": 120,
        "protein": 24.0,
        "carbs": 3.0,
        "fat": 2.0
       }
      ]
     },
     {
      "time": "21:30",
      "name": "Dinner, before the drinks",
      "note": "Grilled chicken, a small spoon of rice, veg in the oil. Eat before the first can",
      "items": [
       {
        "id": "wed-B-3-0",
        "label": "150 g chicken breast (cooked)",
        "kcal": 248,
        "protein": 46.5,
        "carbs": 0.0,
        "fat": 5.4
       },
       {
        "id": "wed-B-3-1",
        "label": "60 g basmati rice, cooked (20 g dry)",
        "kcal": 78,
        "protein": 1.6,
        "carbs": 16.8,
        "fat": 0.2
       },
       {
        "id": "wed-B-3-2",
        "label": "250 g steamed mixed veg",
        "kcal": 88,
        "protein": 5.0,
        "carbs": 15.0,
        "fat": 0.8
       },
       {
        "id": "wed-B-3-3",
        "label": "3 tsp olive oil",
        "kcal": 132,
        "protein": 0.0,
        "carbs": 0.0,
        "fat": 15.0
       }
      ]
     },
     {
      "time": "After drinks",
      "name": "Supper",
      "note": "Yogurt cup, then bed",
      "items": [
       {
        "id": "wed-B-4-0",
        "label": "1 HiPro strawberry Greek yogurt cup (200 g)",
        "kcal": 150,
        "protein": 25.0,
        "carbs": 10.0,
        "fat": 2.0
       }
      ]
     }
    ]
   }
  },
  {
   "day": "Thursday",
   "training": "Rest day",
   "shape": "Two meals plus supper",
   "options": {
    "A": [
     {
      "time": "11:00",
      "name": "Brunch",
      "note": "Eggs with turkey and cheddar on toast, salad, yogurt cup to finish",
      "items": [
       {
        "id": "thu-A-0-0",
        "label": "4 large eggs",
        "kcal": 288,
        "protein": 25.2,
        "carbs": 1.6,
        "fat": 19.2
       },
       {
        "id": "thu-A-0-1",
        "label": "2 slices bran toast",
        "kcal": 110,
        "protein": 4.4,
        "carbs": 19.6,
        "fat": 1.2
       },
       {
        "id": "thu-A-0-2",
        "label": "1 slice cheddar",
        "kcal": 82,
        "protein": 5.0,
        "carbs": 0.2,
        "fat": 6.8
       },
       {
        "id": "thu-A-0-3",
        "label": "2 slices smoked turkey",
        "kcal": 50,
        "protein": 9.0,
        "carbs": 1.0,
        "fat": 1.0
       },
       {
        "id": "thu-A-0-4",
        "label": "150 g salad veg (cucumber, tomato, leaves)",
        "kcal": 30,
        "protein": 1.5,
        "carbs": 5.2,
        "fat": 0.3
       },
       {
        "id": "thu-A-0-5",
        "label": "1 HiPro strawberry Greek yogurt cup (200 g)",
        "kcal": 150,
        "protein": 25.0,
        "carbs": 10.0,
        "fat": 2.0
       }
      ]
     },
     {
      "time": "19:30",
      "name": "Dinner",
      "note": "Pan-seared fillet, rice, veg in the oil",
      "items": [
       {
        "id": "thu-A-1-0",
        "label": "225 g beef fillet (cooked)",
        "kcal": 416,
        "protein": 61.9,
        "carbs": 0.0,
        "fat": 18.0
       },
       {
        "id": "thu-A-1-1",
        "label": "200 g basmati rice, cooked (70 g dry)",
        "kcal": 260,
        "protein": 5.4,
        "carbs": 56.0,
        "fat": 0.6
       },
       {
        "id": "thu-A-1-2",
        "label": "200 g steamed mixed veg",
        "kcal": 70,
        "protein": 4.0,
        "carbs": 12.0,
        "fat": 0.6
       },
       {
        "id": "thu-A-1-3",
        "label": "2 tsp olive oil",
        "kcal": 88,
        "protein": 0.0,
        "carbs": 0.0,
        "fat": 10.0
       }
      ]
     },
     {
      "time": "22:30",
      "name": "Supper",
      "note": "Cottage cheese on toast, bread snack",
      "items": [
       {
        "id": "thu-A-2-0",
        "label": "300 g cottage cheese",
        "kcal": 294,
        "protein": 33.0,
        "carbs": 10.2,
        "fat": 12.9
       },
       {
        "id": "thu-A-2-1",
        "label": "2 slices bran toast",
        "kcal": 110,
        "protein": 4.4,
        "carbs": 19.6,
        "fat": 1.2
       },
       {
        "id": "thu-A-2-2",
        "label": "20 g Balance bread snack",
        "kcal": 80,
        "protein": 4.4,
        "carbs": 13.7,
        "fat": 0.9
       }
      ]
     }
    ],
    "B": [
     {
      "time": "11:00",
      "name": "Brunch",
      "note": "Eggs with turkey and cheddar on toast, salad, yogurt cup to finish",
      "items": [
       {
        "id": "thu-B-0-0",
        "label": "3 large eggs",
        "kcal": 216,
        "protein": 18.9,
        "carbs": 1.2,
        "fat": 14.4
       },
       {
        "id": "thu-B-0-1",
        "label": "2 slices bran toast",
        "kcal": 110,
        "protein": 4.4,
        "carbs": 19.6,
        "fat": 1.2
       },
       {
        "id": "thu-B-0-2",
        "label": "1 slice cheddar",
        "kcal": 82,
        "protein": 5.0,
        "carbs": 0.2,
        "fat": 6.8
       },
       {
        "id": "thu-B-0-3",
        "label": "2 slices smoked turkey",
        "kcal": 50,
        "protein": 9.0,
        "carbs": 1.0,
        "fat": 1.0
       },
       {
        "id": "thu-B-0-4",
        "label": "150 g salad veg (cucumber, tomato, leaves)",
        "kcal": 30,
        "protein": 1.5,
        "carbs": 5.2,
        "fat": 0.3
       },
       {
        "id": "thu-B-0-5",
        "label": "1 HiPro strawberry Greek yogurt cup (200 g)",
        "kcal": 150,
        "protein": 25.0,
        "carbs": 10.0,
        "fat": 2.0
       }
      ]
     },
     {
      "time": "19:00",
      "name": "Dinner, before the drinks",
      "note": "Grilled chicken, rice, veg in the oil. Eat before the first can",
      "items": [
       {
        "id": "thu-B-1-0",
        "label": "230 g chicken breast (cooked)",
        "kcal": 379,
        "protein": 71.3,
        "carbs": 0.0,
        "fat": 8.3
       },
       {
        "id": "thu-B-1-1",
        "label": "150 g basmati rice, cooked (50 g dry)",
        "kcal": 195,
        "protein": 4.1,
        "carbs": 42.0,
        "fat": 0.4
       },
       {
        "id": "thu-B-1-2",
        "label": "200 g steamed mixed veg",
        "kcal": 70,
        "protein": 4.0,
        "carbs": 12.0,
        "fat": 0.6
       },
       {
        "id": "thu-B-1-3",
        "label": "2 tsp olive oil",
        "kcal": 88,
        "protein": 0.0,
        "carbs": 0.0,
        "fat": 10.0
       }
      ]
     },
     {
      "time": "After drinks",
      "name": "Supper",
      "note": "Cottage cheese and turkey on toast, then bed",
      "items": [
       {
        "id": "thu-B-2-0",
        "label": "200 g cottage cheese",
        "kcal": 196,
        "protein": 22.0,
        "carbs": 6.8,
        "fat": 8.6
       },
       {
        "id": "thu-B-2-1",
        "label": "2 slices bran toast",
        "kcal": 110,
        "protein": 4.4,
        "carbs": 19.6,
        "fat": 1.2
       },
       {
        "id": "thu-B-2-2",
        "label": "3 slices smoked turkey",
        "kcal": 75,
        "protein": 13.5,
        "carbs": 1.5,
        "fat": 1.5
       }
      ]
     }
    ]
   }
  },
  {
   "day": "Friday",
   "training": "Padel, evening",
   "shape": "Light dinner, supper",
   "options": {
    "A": [
     {
      "time": "08:30",
      "name": "Breakfast",
      "note": "Boiled eggs, cottage cheese on toast, tomato and cucumber",
      "items": [
       {
        "id": "fri-A-0-0",
        "label": "150 g cottage cheese",
        "kcal": 147,
        "protein": 16.5,
        "carbs": 5.1,
        "fat": 6.4
       },
       {
        "id": "fri-A-0-1",
        "label": "2 slices bran toast",
        "kcal": 110,
        "protein": 4.4,
        "carbs": 19.6,
        "fat": 1.2
       },
       {
        "id": "fri-A-0-2",
        "label": "3 large eggs",
        "kcal": 216,
        "protein": 18.9,
        "carbs": 1.2,
        "fat": 14.4
       },
       {
        "id": "fri-A-0-3",
        "label": "100 g salad veg (cucumber, tomato, leaves)",
        "kcal": 20,
        "protein": 1.0,
        "carbs": 3.5,
        "fat": 0.2
       }
      ]
     },
     {
      "time": "13:30",
      "name": "Lunch",
      "note": "Grilled chicken, rice, veg in the oil",
      "items": [
       {
        "id": "fri-A-1-0",
        "label": "180 g chicken breast (cooked)",
        "kcal": 297,
        "protein": 55.8,
        "carbs": 0.0,
        "fat": 6.5
       },
       {
        "id": "fri-A-1-1",
        "label": "200 g basmati rice, cooked (70 g dry)",
        "kcal": 260,
        "protein": 5.4,
        "carbs": 56.0,
        "fat": 0.6
       },
       {
        "id": "fri-A-1-2",
        "label": "200 g steamed mixed veg",
        "kcal": 70,
        "protein": 4.0,
        "carbs": 12.0,
        "fat": 0.6
       },
       {
        "id": "fri-A-1-3",
        "label": "3 tsp olive oil",
        "kcal": 132,
        "protein": 0.0,
        "carbs": 0.0,
        "fat": 15.0
       }
      ]
     },
     {
      "time": "21:00",
      "name": "Dinner, after padel",
      "note": "Big tuna salad, oil and lemon dressing, cheddar crumbled in",
      "items": [
       {
        "id": "fri-A-2-0",
        "label": "150 g tuna in water (drained)",
        "kcal": 174,
        "protein": 39.0,
        "carbs": 0.0,
        "fat": 1.5
       },
       {
        "id": "fri-A-2-1",
        "label": "200 g salad veg (cucumber, tomato, leaves)",
        "kcal": 40,
        "protein": 2.0,
        "carbs": 7.0,
        "fat": 0.4
       },
       {
        "id": "fri-A-2-2",
        "label": "3 tsp olive oil",
        "kcal": 132,
        "protein": 0.0,
        "carbs": 0.0,
        "fat": 15.0
       },
       {
        "id": "fri-A-2-3",
        "label": "1 slice cheddar",
        "kcal": 82,
        "protein": 5.0,
        "carbs": 0.2,
        "fat": 6.8
       }
      ]
     },
     {
      "time": "23:00",
      "name": "Supper",
      "note": "Yogurt cup, bread snack, apple",
      "items": [
       {
        "id": "fri-A-3-0",
        "label": "1 HiPro strawberry Greek yogurt cup (200 g)",
        "kcal": 150,
        "protein": 25.0,
        "carbs": 10.0,
        "fat": 2.0
       },
       {
        "id": "fri-A-3-1",
        "label": "20 g Balance bread snack",
        "kcal": 80,
        "protein": 4.4,
        "carbs": 13.7,
        "fat": 0.9
       },
       {
        "id": "fri-A-3-2",
        "label": "1 medium apple",
        "kcal": 78,
        "protein": 0.4,
        "carbs": 19.0,
        "fat": 0.2
       }
      ]
     }
    ],
    "B": [
     {
      "time": "08:30",
      "name": "Breakfast",
      "note": "Boiled eggs, cottage cheese on toast, tomato and cucumber",
      "items": [
       {
        "id": "fri-B-0-0",
        "label": "150 g cottage cheese",
        "kcal": 147,
        "protein": 16.5,
        "carbs": 5.1,
        "fat": 6.4
       },
       {
        "id": "fri-B-0-1",
        "label": "2 slices bran toast",
        "kcal": 110,
        "protein": 4.4,
        "carbs": 19.6,
        "fat": 1.2
       },
       {
        "id": "fri-B-0-2",
        "label": "3 large eggs",
        "kcal": 216,
        "protein": 18.9,
        "carbs": 1.2,
        "fat": 14.4
       },
       {
        "id": "fri-B-0-3",
        "label": "100 g salad veg (cucumber, tomato, leaves)",
        "kcal": 20,
        "protein": 1.0,
        "carbs": 3.5,
        "fat": 0.2
       }
      ]
     },
     {
      "time": "13:30",
      "name": "Lunch",
      "note": "Grilled chicken, a small spoon of rice, veg",
      "items": [
       {
        "id": "fri-B-1-0",
        "label": "150 g chicken breast (cooked)",
        "kcal": 248,
        "protein": 46.5,
        "carbs": 0.0,
        "fat": 5.4
       },
       {
        "id": "fri-B-1-1",
        "label": "60 g basmati rice, cooked (20 g dry)",
        "kcal": 78,
        "protein": 1.6,
        "carbs": 16.8,
        "fat": 0.2
       },
       {
        "id": "fri-B-1-2",
        "label": "200 g steamed mixed veg",
        "kcal": 70,
        "protein": 4.0,
        "carbs": 12.0,
        "fat": 0.6
       },
       {
        "id": "fri-B-1-3",
        "label": "1 tsp olive oil",
        "kcal": 44,
        "protein": 0.0,
        "carbs": 0.0,
        "fat": 5.0
       }
      ]
     },
     {
      "time": "21:00",
      "name": "Dinner, before the drinks",
      "note": "Tuna salad wrap with cheddar. Eat before the first can",
      "items": [
       {
        "id": "fri-B-2-0",
        "label": "150 g tuna in water (drained)",
        "kcal": 174,
        "protein": 39.0,
        "carbs": 0.0,
        "fat": 1.5
       },
       {
        "id": "fri-B-2-1",
        "label": "200 g salad veg (cucumber, tomato, leaves)",
        "kcal": 40,
        "protein": 2.0,
        "carbs": 7.0,
        "fat": 0.4
       },
       {
        "id": "fri-B-2-2",
        "label": "1 tsp olive oil",
        "kcal": 44,
        "protein": 0.0,
        "carbs": 0.0,
        "fat": 5.0
       },
       {
        "id": "fri-B-2-3",
        "label": "1 large bran tortilla (90 g)",
        "kcal": 250,
        "protein": 7.0,
        "carbs": 53.0,
        "fat": 1.0
       },
       {
        "id": "fri-B-2-4",
        "label": "1 slice cheddar",
        "kcal": 82,
        "protein": 5.0,
        "carbs": 0.2,
        "fat": 6.8
       }
      ]
     },
     {
      "time": "After drinks",
      "name": "Supper",
      "note": "Yogurt cup and turkey, then bed",
      "items": [
       {
        "id": "fri-B-3-0",
        "label": "1 HiPro strawberry Greek yogurt cup (200 g)",
        "kcal": 150,
        "protein": 25.0,
        "carbs": 10.0,
        "fat": 2.0
       },
       {
        "id": "fri-B-3-1",
        "label": "2 slices smoked turkey",
        "kcal": 50,
        "protein": 9.0,
        "carbs": 1.0,
        "fat": 1.0
       }
      ]
     }
    ]
   }
  },
  {
   "day": "Saturday",
   "training": "Gym, evening",
   "shape": "Heavy dinner, no supper",
   "options": {
    "A": [
     {
      "time": "10:00",
      "name": "Breakfast",
      "note": "Egg, turkey and cheddar wrap, salad on the side",
      "items": [
       {
        "id": "sat-A-0-0",
        "label": "3 large eggs",
        "kcal": 216,
        "protein": 18.9,
        "carbs": 1.2,
        "fat": 14.4
       },
       {
        "id": "sat-A-0-1",
        "label": "2 slices smoked turkey",
        "kcal": 50,
        "protein": 9.0,
        "carbs": 1.0,
        "fat": 1.0
       },
       {
        "id": "sat-A-0-2",
        "label": "1 slice cheddar",
        "kcal": 82,
        "protein": 5.0,
        "carbs": 0.2,
        "fat": 6.8
       },
       {
        "id": "sat-A-0-3",
        "label": "1 large bran tortilla (90 g)",
        "kcal": 250,
        "protein": 7.0,
        "carbs": 53.0,
        "fat": 1.0
       },
       {
        "id": "sat-A-0-4",
        "label": "100 g salad veg (cucumber, tomato, leaves)",
        "kcal": 20,
        "protein": 1.0,
        "carbs": 3.5,
        "fat": 0.2
       }
      ]
     },
     {
      "time": "14:30",
      "name": "Lunch",
      "note": "Tuna with rice and veg, oil over the top",
      "items": [
       {
        "id": "sat-A-1-0",
        "label": "120 g tuna in water (drained)",
        "kcal": 139,
        "protein": 31.2,
        "carbs": 0.0,
        "fat": 1.2
       },
       {
        "id": "sat-A-1-1",
        "label": "110 g basmati rice, cooked (40 g dry)",
        "kcal": 143,
        "protein": 3.0,
        "carbs": 30.8,
        "fat": 0.3
       },
       {
        "id": "sat-A-1-2",
        "label": "150 g steamed mixed veg",
        "kcal": 52,
        "protein": 3.0,
        "carbs": 9.0,
        "fat": 0.4
       },
       {
        "id": "sat-A-1-3",
        "label": "2 tsp olive oil",
        "kcal": 88,
        "protein": 0.0,
        "carbs": 0.0,
        "fat": 10.0
       }
      ]
     },
     {
      "time": "20:30",
      "name": "After the gym",
      "note": "Shake with water, banana on the side",
      "items": [
       {
        "id": "sat-A-2-0",
        "label": "1 scoop whey protein (30 g) in water",
        "kcal": 120,
        "protein": 24.0,
        "carbs": 3.0,
        "fat": 2.0
       },
       {
        "id": "sat-A-2-1",
        "label": "1 medium banana",
        "kcal": 105,
        "protein": 1.3,
        "carbs": 27.0,
        "fat": 0.4
       },
       {
        "id": "sat-A-2-2",
        "label": "1 tsp honey",
        "kcal": 21,
        "protein": 0.0,
        "carbs": 5.7,
        "fat": 0.0
       }
      ]
     },
     {
      "time": "21:30",
      "name": "Dinner",
      "note": "Mince with onion, garlic and spices, veg in the oil",
      "items": [
       {
        "id": "sat-A-3-0",
        "label": "270 g 5% minced beef (cooked)",
        "kcal": 446,
        "protein": 72.9,
        "carbs": 0.0,
        "fat": 17.6
       },
       {
        "id": "sat-A-3-1",
        "label": "250 g steamed mixed veg",
        "kcal": 88,
        "protein": 5.0,
        "carbs": 15.0,
        "fat": 0.8
       },
       {
        "id": "sat-A-3-2",
        "label": "3 tsp olive oil",
        "kcal": 132,
        "protein": 0.0,
        "carbs": 0.0,
        "fat": 15.0
       }
      ]
     }
    ],
    "B": [
     {
      "time": "10:00",
      "name": "Breakfast",
      "note": "Egg and turkey wrap, salad on the side",
      "items": [
       {
        "id": "sat-B-0-0",
        "label": "3 large eggs",
        "kcal": 216,
        "protein": 18.9,
        "carbs": 1.2,
        "fat": 14.4
       },
       {
        "id": "sat-B-0-1",
        "label": "2 slices smoked turkey",
        "kcal": 50,
        "protein": 9.0,
        "carbs": 1.0,
        "fat": 1.0
       },
       {
        "id": "sat-B-0-2",
        "label": "1 large bran tortilla (90 g)",
        "kcal": 250,
        "protein": 7.0,
        "carbs": 53.0,
        "fat": 1.0
       },
       {
        "id": "sat-B-0-3",
        "label": "100 g salad veg (cucumber, tomato, leaves)",
        "kcal": 20,
        "protein": 1.0,
        "carbs": 3.5,
        "fat": 0.2
       }
      ]
     },
     {
      "time": "14:30",
      "name": "Lunch",
      "note": "Tuna with a small spoon of rice and veg",
      "items": [
       {
        "id": "sat-B-1-0",
        "label": "120 g tuna in water (drained)",
        "kcal": 139,
        "protein": 31.2,
        "carbs": 0.0,
        "fat": 1.2
       },
       {
        "id": "sat-B-1-1",
        "label": "60 g basmati rice, cooked (20 g dry)",
        "kcal": 78,
        "protein": 1.6,
        "carbs": 16.8,
        "fat": 0.2
       },
       {
        "id": "sat-B-1-2",
        "label": "150 g steamed mixed veg",
        "kcal": 52,
        "protein": 3.0,
        "carbs": 9.0,
        "fat": 0.4
       },
       {
        "id": "sat-B-1-3",
        "label": "1 tsp olive oil",
        "kcal": 44,
        "protein": 0.0,
        "carbs": 0.0,
        "fat": 5.0
       }
      ]
     },
     {
      "time": "20:30",
      "name": "After the gym",
      "note": "Shake with water",
      "items": [
       {
        "id": "sat-B-2-0",
        "label": "1 scoop whey protein (30 g) in water",
        "kcal": 120,
        "protein": 24.0,
        "carbs": 3.0,
        "fat": 2.0
       }
      ]
     },
     {
      "time": "21:30",
      "name": "Dinner, before the drinks",
      "note": "Mince with onion, garlic and spices, veg. Eat before the first can",
      "items": [
       {
        "id": "sat-B-3-0",
        "label": "190 g 5% minced beef (cooked)",
        "kcal": 314,
        "protein": 51.3,
        "carbs": 0.0,
        "fat": 12.3
       },
       {
        "id": "sat-B-3-1",
        "label": "250 g steamed mixed veg",
        "kcal": 88,
        "protein": 5.0,
        "carbs": 15.0,
        "fat": 0.8
       },
       {
        "id": "sat-B-3-2",
        "label": "1 tsp olive oil",
        "kcal": 44,
        "protein": 0.0,
        "carbs": 0.0,
        "fat": 5.0
       }
      ]
     },
     {
      "time": "After drinks",
      "name": "Supper",
      "note": "Cottage cheese on toast, then bed",
      "items": [
       {
        "id": "sat-B-4-0",
        "label": "200 g cottage cheese",
        "kcal": 196,
        "protein": 22.0,
        "carbs": 6.8,
        "fat": 8.6
       },
       {
        "id": "sat-B-4-1",
        "label": "2 slices bran toast",
        "kcal": 110,
        "protein": 4.4,
        "carbs": 19.6,
        "fat": 1.2
       }
      ]
     }
    ]
   }
  },
  {
   "day": "Sunday",
   "training": "Rest day",
   "shape": "Two meals plus supper",
   "options": {
    "A": [
     {
      "time": "11:00",
      "name": "Brunch",
      "note": "Big omelette with cheddar and turkey, toast, salad in the oil",
      "items": [
       {
        "id": "sun-A-0-0",
        "label": "4 large eggs",
        "kcal": 288,
        "protein": 25.2,
        "carbs": 1.6,
        "fat": 19.2
       },
       {
        "id": "sun-A-0-1",
        "label": "2 slices bran toast",
        "kcal": 110,
        "protein": 4.4,
        "carbs": 19.6,
        "fat": 1.2
       },
       {
        "id": "sun-A-0-2",
        "label": "2 slices cheddar",
        "kcal": 164,
        "protein": 10.0,
        "carbs": 0.4,
        "fat": 13.6
       },
       {
        "id": "sun-A-0-3",
        "label": "2 slices smoked turkey",
        "kcal": 50,
        "protein": 9.0,
        "carbs": 1.0,
        "fat": 1.0
       },
       {
        "id": "sun-A-0-4",
        "label": "150 g salad veg (cucumber, tomato, leaves)",
        "kcal": 30,
        "protein": 1.5,
        "carbs": 5.2,
        "fat": 0.3
       },
       {
        "id": "sun-A-0-5",
        "label": "1 tsp olive oil",
        "kcal": 44,
        "protein": 0.0,
        "carbs": 0.0,
        "fat": 5.0
       }
      ]
     },
     {
      "time": "18:30",
      "name": "Dinner",
      "note": "Grilled chicken, rice, veg in the oil",
      "items": [
       {
        "id": "sun-A-1-0",
        "label": "225 g chicken breast (cooked)",
        "kcal": 371,
        "protein": 69.8,
        "carbs": 0.0,
        "fat": 8.1
       },
       {
        "id": "sun-A-1-1",
        "label": "200 g basmati rice, cooked (70 g dry)",
        "kcal": 260,
        "protein": 5.4,
        "carbs": 56.0,
        "fat": 0.6
       },
       {
        "id": "sun-A-1-2",
        "label": "200 g steamed mixed veg",
        "kcal": 70,
        "protein": 4.0,
        "carbs": 12.0,
        "fat": 0.6
       },
       {
        "id": "sun-A-1-3",
        "label": "2 tsp olive oil",
        "kcal": 88,
        "protein": 0.0,
        "carbs": 0.0,
        "fat": 10.0
       }
      ]
     },
     {
      "time": "22:00",
      "name": "Supper",
      "note": "Yogurt cup, cottage cheese and turkey on toast, apple",
      "items": [
       {
        "id": "sun-A-2-0",
        "label": "1 HiPro strawberry Greek yogurt cup (200 g)",
        "kcal": 150,
        "protein": 25.0,
        "carbs": 10.0,
        "fat": 2.0
       },
       {
        "id": "sun-A-2-1",
        "label": "150 g cottage cheese",
        "kcal": 147,
        "protein": 16.5,
        "carbs": 5.1,
        "fat": 6.4
       },
       {
        "id": "sun-A-2-2",
        "label": "2 slices bran toast",
        "kcal": 110,
        "protein": 4.4,
        "carbs": 19.6,
        "fat": 1.2
       },
       {
        "id": "sun-A-2-3",
        "label": "1 slice smoked turkey",
        "kcal": 25,
        "protein": 4.5,
        "carbs": 0.5,
        "fat": 0.5
       },
       {
        "id": "sun-A-2-4",
        "label": "1 medium apple",
        "kcal": 78,
        "protein": 0.4,
        "carbs": 19.0,
        "fat": 0.2
       }
      ]
     }
    ],
    "B": [
     {
      "time": "11:00",
      "name": "Brunch",
      "note": "Big omelette with turkey, toast, salad",
      "items": [
       {
        "id": "sun-B-0-0",
        "label": "4 large eggs",
        "kcal": 288,
        "protein": 25.2,
        "carbs": 1.6,
        "fat": 19.2
       },
       {
        "id": "sun-B-0-1",
        "label": "2 slices bran toast",
        "kcal": 110,
        "protein": 4.4,
        "carbs": 19.6,
        "fat": 1.2
       },
       {
        "id": "sun-B-0-2",
        "label": "2 slices smoked turkey",
        "kcal": 50,
        "protein": 9.0,
        "carbs": 1.0,
        "fat": 1.0
       },
       {
        "id": "sun-B-0-3",
        "label": "150 g salad veg (cucumber, tomato, leaves)",
        "kcal": 30,
        "protein": 1.5,
        "carbs": 5.2,
        "fat": 0.3
       }
      ]
     },
     {
      "time": "18:30",
      "name": "Dinner, before the drinks",
      "note": "Grilled chicken, rice, veg in the oil. Eat before the first can",
      "items": [
       {
        "id": "sun-B-1-0",
        "label": "260 g chicken breast (cooked)",
        "kcal": 429,
        "protein": 80.6,
        "carbs": 0.0,
        "fat": 9.4
       },
       {
        "id": "sun-B-1-1",
        "label": "150 g basmati rice, cooked (50 g dry)",
        "kcal": 195,
        "protein": 4.1,
        "carbs": 42.0,
        "fat": 0.4
       },
       {
        "id": "sun-B-1-2",
        "label": "200 g steamed mixed veg",
        "kcal": 70,
        "protein": 4.0,
        "carbs": 12.0,
        "fat": 0.6
       },
       {
        "id": "sun-B-1-3",
        "label": "2 tsp olive oil",
        "kcal": 88,
        "protein": 0.0,
        "carbs": 0.0,
        "fat": 10.0
       }
      ]
     },
     {
      "time": "After drinks",
      "name": "Supper",
      "note": "Yogurt cup, cottage cheese and turkey on toast, then bed",
      "items": [
       {
        "id": "sun-B-2-0",
        "label": "1 HiPro strawberry Greek yogurt cup (200 g)",
        "kcal": 150,
        "protein": 25.0,
        "carbs": 10.0,
        "fat": 2.0
       },
       {
        "id": "sun-B-2-1",
        "label": "150 g cottage cheese",
        "kcal": 147,
        "protein": 16.5,
        "carbs": 5.1,
        "fat": 6.4
       },
       {
        "id": "sun-B-2-2",
        "label": "2 slices bran toast",
        "kcal": 110,
        "protein": 4.4,
        "carbs": 19.6,
        "fat": 1.2
       },
       {
        "id": "sun-B-2-3",
        "label": "2 slices smoked turkey",
        "kcal": 50,
        "protein": 9.0,
        "carbs": 1.0,
        "fat": 1.0
       }
      ]
     }
    ]
   }
  }
 ]
};
