// Generated by Projects/Documents/Drafts/Andrew Meal Plan (generator).py. Do not edit by hand.
window.PLAN = {
 "targets": {
  "A": {
   "label": "Non-drinking day",
   "kcal": [
    1950,
    2050
   ],
   "protein": [
    175,
    185
   ],
   "carbs": [
    135,
    155
   ],
   "fat": [
    65,
    75
   ]
  },
  "B": {
   "label": "Drinking day",
   "kcal": [
    1200,
    1400
   ],
   "protein": [
    175,
    185
   ],
   "carbs": [
    60,
    140
   ],
   "fat": [
    20,
    40
   ]
  }
 },
 "drinks": {
  "name": "Meister Max 500 ml, 8%",
  "cans": 3,
  "kcalPerCan": 300,
  "carbsPerCan": 12
 },
 "days": [
  {
   "day": "Monday",
   "training": "Gym, evening",
   "shape": "Heavy dinner, no supper",
   "options": {
    "A": [
     {
      "time": "08:30",
      "name": "Breakfast",
      "note": "Scrambled eggs with turkey, toast, salad in the oil",
      "items": [
       {
        "id": "mon-A-0-0",
        "label": "3 large eggs",
        "kcal": 254,
        "protein": 25.0,
        "carbs": 0.0,
        "fat": 17.0
       },
       {
        "id": "mon-A-0-1",
        "label": "2 slices Domty high protein toast",
        "kcal": 170,
        "protein": 9.2,
        "carbs": 28.4,
        "fat": 2.2
       },
       {
        "id": "mon-A-0-2",
        "label": "60 g smoked turkey slices",
        "kcal": 68,
        "protein": 13.8,
        "carbs": 0.7,
        "fat": 1.1
       },
       {
        "id": "mon-A-0-3",
        "label": "100 g salad veg (cucumber, tomato, leaves)",
        "kcal": 13,
        "protein": 0.9,
        "carbs": 1.9,
        "fat": 0.3
       },
       {
        "id": "mon-A-0-4",
        "label": "1 teaspoon olive oil",
        "kcal": 41,
        "protein": 0.0,
        "carbs": 0.0,
        "fat": 4.6
       }
      ]
     },
     {
      "time": "13:30",
      "name": "Lunch",
      "note": "Grilled chicken, a small spoon of rice (the fries tonight are the carbs), steamed veg with the oil over it",
      "items": [
       {
        "id": "mon-A-1-0",
        "label": "90 g chicken breast (cooked)",
        "kcal": 133,
        "protein": 28.8,
        "carbs": 0.0,
        "fat": 2.0
       },
       {
        "id": "mon-A-1-1",
        "label": "60 g basmati rice (cooked)",
        "kcal": 70,
        "protein": 1.7,
        "carbs": 15.9,
        "fat": 0.4
       },
       {
        "id": "mon-A-1-2",
        "label": "200 g steamed mixed veg",
        "kcal": 84,
        "protein": 6.6,
        "carbs": 13.2,
        "fat": 1.0
       },
       {
        "id": "mon-A-1-3",
        "label": "1 teaspoon olive oil",
        "kcal": 41,
        "protein": 0.0,
        "carbs": 0.0,
        "fat": 4.6
       }
      ]
     },
     {
      "time": "20:45",
      "name": "After the gym",
      "note": "Shake with water, honey stirred in",
      "items": [
       {
        "id": "mon-A-2-0",
        "label": "1 scoop whey protein (33 g) in water",
        "kcal": 110,
        "protein": 26.0,
        "carbs": 1.0,
        "fat": 0.5
       },
       {
        "id": "mon-A-2-1",
        "label": "1 teaspoon honey",
        "kcal": 20,
        "protein": 0.0,
        "carbs": 5.3,
        "fat": 0.0
       }
      ]
     },
     {
      "time": "21:30",
      "name": "Dinner",
      "note": "Pan-seared fillet, thin fries from the air fryer with no oil, veg in the oil",
      "items": [
       {
        "id": "mon-A-3-0",
        "label": "200 g beef fillet (cooked)",
        "kcal": 376,
        "protein": 58.2,
        "carbs": 0.0,
        "fat": 16.0
       },
       {
        "id": "mon-A-3-1",
        "label": "200 g Farm Frites thin fries (air-fried, no oil)",
        "kcal": 378,
        "protein": 6.4,
        "carbs": 70.6,
        "fat": 9.8
       },
       {
        "id": "mon-A-3-2",
        "label": "250 g steamed mixed veg",
        "kcal": 105,
        "protein": 8.2,
        "carbs": 16.5,
        "fat": 1.2
       },
       {
        "id": "mon-A-3-3",
        "label": "3 teaspoons olive oil",
        "kcal": 123,
        "protein": 0.0,
        "carbs": 0.0,
        "fat": 13.7
       }
      ]
     }
    ],
    "B": [
     {
      "time": "08:30",
      "name": "Breakfast",
      "note": "Scrambled egg with cheddar melted in, toast, salad",
      "items": [
       {
        "id": "mon-B-0-0",
        "label": "1 large egg",
        "kcal": 85,
        "protein": 8.3,
        "carbs": 0.0,
        "fat": 5.7
       },
       {
        "id": "mon-B-0-1",
        "label": "2 slices Domty high protein toast",
        "kcal": 170,
        "protein": 9.2,
        "carbs": 28.4,
        "fat": 2.2
       },
       {
        "id": "mon-B-0-2",
        "label": "50 g salad veg (cucumber, tomato, leaves)",
        "kcal": 6,
        "protein": 0.5,
        "carbs": 0.9,
        "fat": 0.1
       },
       {
        "id": "mon-B-0-3",
        "label": "10 g cheddar slices",
        "kcal": 30,
        "protein": 1.8,
        "carbs": 0.5,
        "fat": 2.3
       }
      ]
     },
     {
      "time": "13:30",
      "name": "Lunch",
      "note": "Grilled chicken, steamed veg, no rice or oil today. The toast tonight is the carbs",
      "items": [
       {
        "id": "mon-B-1-0",
        "label": "170 g chicken breast (cooked)",
        "kcal": 252,
        "protein": 54.4,
        "carbs": 0.0,
        "fat": 3.7
       },
       {
        "id": "mon-B-1-1",
        "label": "100 g steamed mixed veg",
        "kcal": 42,
        "protein": 3.3,
        "carbs": 6.6,
        "fat": 0.5
       }
      ]
     },
     {
      "time": "20:45",
      "name": "After the gym",
      "note": "Shake with water",
      "items": [
       {
        "id": "mon-B-2-0",
        "label": "1 scoop whey protein (33 g) in water",
        "kcal": 110,
        "protein": 26.0,
        "carbs": 1.0,
        "fat": 0.5
       }
      ]
     },
     {
      "time": "21:30",
      "name": "Dinner, before the drinks",
      "note": "Tuna and veg with toast. Eat this before the first can",
      "items": [
       {
        "id": "mon-B-3-0",
        "label": "190 g tuna in water (drained)",
        "kcal": 207,
        "protein": 47.3,
        "carbs": 0.0,
        "fat": 1.9
       },
       {
        "id": "mon-B-3-1",
        "label": "100 g steamed mixed veg",
        "kcal": 42,
        "protein": 3.3,
        "carbs": 6.6,
        "fat": 0.5
       },
       {
        "id": "mon-B-3-2",
        "label": "2 slices Domty high protein toast",
        "kcal": 170,
        "protein": 9.2,
        "carbs": 28.4,
        "fat": 2.2
       }
      ]
     },
     {
      "time": "After drinks",
      "name": "Supper",
      "note": "Cottage cheese on toast, then bed",
      "items": [
       {
        "id": "mon-B-4-0",
        "label": "50 g cottage cheese",
        "kcal": 34,
        "protein": 5.3,
        "carbs": 1.6,
        "fat": 0.8
       },
       {
        "id": "mon-B-4-1",
        "label": "2 slices Domty high protein toast",
        "kcal": 170,
        "protein": 9.2,
        "carbs": 28.4,
        "fat": 2.2
       }
      ]
     }
    ]
   }
  },
  {
   "day": "Tuesday",
   "training": "Padel, evening",
   "shape": "Light dinner, supper",
   "options": {
    "A": [
     {
      "time": "09:00",
      "name": "Breakfast",
      "note": "Yogurt cup, crisps, one boiled egg. Quick one",
      "items": [
       {
        "id": "tue-A-0-0",
        "label": "1 HiPro strawberry Greek yogurt cup (200 g)",
        "kcal": 127,
        "protein": 18.0,
        "carbs": 12.0,
        "fat": 0.9
       },
       {
        "id": "tue-A-0-1",
        "label": "20 g Balance protein crisps",
        "kcal": 80,
        "protein": 4.7,
        "carbs": 10.9,
        "fat": 2.5
       },
       {
        "id": "tue-A-0-2",
        "label": "1 large egg",
        "kcal": 85,
        "protein": 8.3,
        "carbs": 0.0,
        "fat": 5.7
       }
      ]
     },
     {
      "time": "13:30",
      "name": "Lunch",
      "note": "Mince cooked with onion and spices, rice, veg",
      "items": [
       {
        "id": "tue-A-1-0",
        "label": "190 g extra lean minced beef (cooked)",
        "kcal": 260,
        "protein": 46.9,
        "carbs": 0.0,
        "fat": 8.0
       },
       {
        "id": "tue-A-1-1",
        "label": "200 g steamed mixed veg",
        "kcal": 84,
        "protein": 6.6,
        "carbs": 13.2,
        "fat": 1.0
       },
       {
        "id": "tue-A-1-2",
        "label": "270 g basmati rice (cooked)",
        "kcal": 316,
        "protein": 7.6,
        "carbs": 71.6,
        "fat": 1.9
       },
       {
        "id": "tue-A-1-3",
        "label": "4 teaspoons olive oil",
        "kcal": 164,
        "protein": 0.0,
        "carbs": 0.0,
        "fat": 18.2
       }
      ]
     },
     {
      "time": "21:00",
      "name": "Dinner, after padel",
      "note": "Turkey and cheddar omelette, salad in the oil",
      "items": [
       {
        "id": "tue-A-2-0",
        "label": "3 large eggs",
        "kcal": 254,
        "protein": 25.0,
        "carbs": 0.0,
        "fat": 17.0
       },
       {
        "id": "tue-A-2-1",
        "label": "80 g smoked turkey slices",
        "kcal": 91,
        "protein": 18.4,
        "carbs": 1.0,
        "fat": 1.5
       },
       {
        "id": "tue-A-2-2",
        "label": "20 g cheddar slices",
        "kcal": 59,
        "protein": 3.6,
        "carbs": 1.0,
        "fat": 4.6
       },
       {
        "id": "tue-A-2-3",
        "label": "150 g salad veg (cucumber, tomato, leaves)",
        "kcal": 20,
        "protein": 1.4,
        "carbs": 2.8,
        "fat": 0.4
       },
       {
        "id": "tue-A-2-4",
        "label": "1 teaspoon olive oil",
        "kcal": 41,
        "protein": 0.0,
        "carbs": 0.0,
        "fat": 4.6
       }
      ]
     },
     {
      "time": "23:00",
      "name": "Supper",
      "note": "Cottage cheese on toast, black pepper",
      "items": [
       {
        "id": "tue-A-3-0",
        "label": "300 g cottage cheese",
        "kcal": 204,
        "protein": 31.8,
        "carbs": 9.9,
        "fat": 4.5
       },
       {
        "id": "tue-A-3-1",
        "label": "2 slices Domty high protein toast",
        "kcal": 170,
        "protein": 9.2,
        "carbs": 28.4,
        "fat": 2.2
       }
      ]
     }
    ],
    "B": [
     {
      "time": "09:00",
      "name": "Breakfast",
      "note": "Yogurt cup, crisps, one boiled egg",
      "items": [
       {
        "id": "tue-B-0-0",
        "label": "1 HiPro strawberry Greek yogurt cup (200 g)",
        "kcal": 127,
        "protein": 18.0,
        "carbs": 12.0,
        "fat": 0.9
       },
       {
        "id": "tue-B-0-1",
        "label": "10 g Balance protein crisps",
        "kcal": 40,
        "protein": 2.3,
        "carbs": 5.4,
        "fat": 1.3
       },
       {
        "id": "tue-B-0-2",
        "label": "1 large egg",
        "kcal": 85,
        "protein": 8.3,
        "carbs": 0.0,
        "fat": 5.7
       }
      ]
     },
     {
      "time": "13:30",
      "name": "Lunch",
      "note": "Mince with onion and spices, veg, no rice today. The wrap tonight is the carbs",
      "items": [
       {
        "id": "tue-B-1-0",
        "label": "110 g extra lean minced beef (cooked)",
        "kcal": 151,
        "protein": 27.2,
        "carbs": 0.0,
        "fat": 4.6
       },
       {
        "id": "tue-B-1-1",
        "label": "100 g steamed mixed veg",
        "kcal": 42,
        "protein": 3.3,
        "carbs": 6.6,
        "fat": 0.5
       }
      ]
     },
     {
      "time": "21:00",
      "name": "Dinner, before the drinks",
      "note": "Chicken and veg wrap. Eat before the first can",
      "items": [
       {
        "id": "tue-B-2-0",
        "label": "260 g chicken breast (cooked)",
        "kcal": 385,
        "protein": 83.2,
        "carbs": 0.0,
        "fat": 5.7
       },
       {
        "id": "tue-B-2-1",
        "label": "100 g steamed mixed veg",
        "kcal": 42,
        "protein": 3.3,
        "carbs": 6.6,
        "fat": 0.5
       },
       {
        "id": "tue-B-2-2",
        "label": "1 large bran tortilla (90 g)",
        "kcal": 250,
        "protein": 7.0,
        "carbs": 53.0,
        "fat": 1.0
       }
      ]
     },
     {
      "time": "After drinks",
      "name": "Supper",
      "note": "Cottage cheese and turkey on toast, then bed",
      "items": [
       {
        "id": "tue-B-3-0",
        "label": "50 g cottage cheese",
        "kcal": 34,
        "protein": 5.3,
        "carbs": 1.6,
        "fat": 0.8
       },
       {
        "id": "tue-B-3-1",
        "label": "2 slices Domty high protein toast",
        "kcal": 170,
        "protein": 9.2,
        "carbs": 28.4,
        "fat": 2.2
       },
       {
        "id": "tue-B-3-2",
        "label": "40 g smoked turkey slices",
        "kcal": 46,
        "protein": 9.2,
        "carbs": 0.5,
        "fat": 0.8
       }
      ]
     }
    ]
   }
  },
  {
   "day": "Wednesday",
   "training": "Gym, evening",
   "shape": "Heavy dinner, no supper",
   "options": {
    "A": [
     {
      "time": "08:30",
      "name": "Breakfast",
      "note": "Cottage cheese on toast, two boiled eggs, turkey, tomato and cucumber",
      "items": [
       {
        "id": "wed-A-0-0",
        "label": "150 g cottage cheese",
        "kcal": 102,
        "protein": 15.9,
        "carbs": 4.9,
        "fat": 2.2
       },
       {
        "id": "wed-A-0-1",
        "label": "2 slices Domty high protein toast",
        "kcal": 170,
        "protein": 9.2,
        "carbs": 28.4,
        "fat": 2.2
       },
       {
        "id": "wed-A-0-2",
        "label": "2 large eggs",
        "kcal": 169,
        "protein": 16.7,
        "carbs": 0.0,
        "fat": 11.3
       },
       {
        "id": "wed-A-0-3",
        "label": "20 g smoked turkey slices",
        "kcal": 23,
        "protein": 4.6,
        "carbs": 0.2,
        "fat": 0.4
       },
       {
        "id": "wed-A-0-4",
        "label": "100 g salad veg (cucumber, tomato, leaves)",
        "kcal": 13,
        "protein": 0.9,
        "carbs": 1.9,
        "fat": 0.3
       }
      ]
     },
     {
      "time": "13:30",
      "name": "Lunch",
      "note": "Tuna on toast, salad in the oil. Tuna in oil, drained",
      "items": [
       {
        "id": "wed-A-1-0",
        "label": "110 g tuna in sunflower oil (drained)",
        "kcal": 175,
        "protein": 27.9,
        "carbs": 0.0,
        "fat": 7.0
       },
       {
        "id": "wed-A-1-1",
        "label": "2 slices Domty high protein toast",
        "kcal": 170,
        "protein": 9.2,
        "carbs": 28.4,
        "fat": 2.2
       },
       {
        "id": "wed-A-1-2",
        "label": "150 g salad veg (cucumber, tomato, leaves)",
        "kcal": 20,
        "protein": 1.4,
        "carbs": 2.8,
        "fat": 0.4
       },
       {
        "id": "wed-A-1-3",
        "label": "3 teaspoons olive oil",
        "kcal": 123,
        "protein": 0.0,
        "carbs": 0.0,
        "fat": 13.7
       }
      ]
     },
     {
      "time": "20:45",
      "name": "After the gym",
      "note": "Shake with water",
      "items": [
       {
        "id": "wed-A-2-0",
        "label": "1 scoop whey protein (33 g) in water",
        "kcal": 110,
        "protein": 26.0,
        "carbs": 1.0,
        "fat": 0.5
       }
      ]
     },
     {
      "time": "21:30",
      "name": "Dinner",
      "note": "Grilled chicken, thin fries from the air fryer with no oil, veg in the oil. No rice tonight",
      "items": [
       {
        "id": "wed-A-3-0",
        "label": "180 g chicken breast (cooked)",
        "kcal": 266,
        "protein": 57.6,
        "carbs": 0.0,
        "fat": 4.0
       },
       {
        "id": "wed-A-3-1",
        "label": "200 g Farm Frites thin fries (air-fried, no oil)",
        "kcal": 378,
        "protein": 6.4,
        "carbs": 70.6,
        "fat": 9.8
       },
       {
        "id": "wed-A-3-2",
        "label": "250 g steamed mixed veg",
        "kcal": 105,
        "protein": 8.2,
        "carbs": 16.5,
        "fat": 1.2
       },
       {
        "id": "wed-A-3-3",
        "label": "4 teaspoons olive oil",
        "kcal": 164,
        "protein": 0.0,
        "carbs": 0.0,
        "fat": 18.2
       }
      ]
     }
    ],
    "B": [
     {
      "time": "08:30",
      "name": "Breakfast",
      "note": "Cottage cheese on toast, turkey on top, tomato and cucumber",
      "items": [
       {
        "id": "wed-B-0-0",
        "label": "50 g cottage cheese",
        "kcal": 34,
        "protein": 5.3,
        "carbs": 1.6,
        "fat": 0.8
       },
       {
        "id": "wed-B-0-1",
        "label": "2 slices Domty high protein toast",
        "kcal": 170,
        "protein": 9.2,
        "carbs": 28.4,
        "fat": 2.2
       },
       {
        "id": "wed-B-0-2",
        "label": "40 g smoked turkey slices",
        "kcal": 46,
        "protein": 9.2,
        "carbs": 0.5,
        "fat": 0.8
       },
       {
        "id": "wed-B-0-3",
        "label": "50 g salad veg (cucumber, tomato, leaves)",
        "kcal": 6,
        "protein": 0.5,
        "carbs": 0.9,
        "fat": 0.1
       }
      ]
     },
     {
      "time": "13:30",
      "name": "Lunch",
      "note": "Tuna on toast with salad. Tuna in water today",
      "items": [
       {
        "id": "wed-B-1-0",
        "label": "170 g tuna in water (drained)",
        "kcal": 185,
        "protein": 42.3,
        "carbs": 0.0,
        "fat": 1.7
       },
       {
        "id": "wed-B-1-1",
        "label": "2 slices Domty high protein toast",
        "kcal": 170,
        "protein": 9.2,
        "carbs": 28.4,
        "fat": 2.2
       },
       {
        "id": "wed-B-1-2",
        "label": "50 g salad veg (cucumber, tomato, leaves)",
        "kcal": 6,
        "protein": 0.5,
        "carbs": 0.9,
        "fat": 0.1
       }
      ]
     },
     {
      "time": "20:45",
      "name": "After the gym",
      "note": "Shake with water",
      "items": [
       {
        "id": "wed-B-2-0",
        "label": "1 scoop whey protein (33 g) in water",
        "kcal": 110,
        "protein": 26.0,
        "carbs": 1.0,
        "fat": 0.5
       }
      ]
     },
     {
      "time": "21:30",
      "name": "Dinner, before the drinks",
      "note": "Grilled chicken, veg in the oil. Eat before the first can",
      "items": [
       {
        "id": "wed-B-3-0",
        "label": "170 g chicken breast (cooked)",
        "kcal": 252,
        "protein": 54.4,
        "carbs": 0.0,
        "fat": 3.7
       },
       {
        "id": "wed-B-3-1",
        "label": "100 g steamed mixed veg",
        "kcal": 42,
        "protein": 3.3,
        "carbs": 6.6,
        "fat": 0.5
       },
       {
        "id": "wed-B-3-2",
        "label": "2 teaspoons olive oil",
        "kcal": 82,
        "protein": 0.0,
        "carbs": 0.0,
        "fat": 9.1
       }
      ]
     },
     {
      "time": "After drinks",
      "name": "Supper",
      "note": "Yogurt cup, then bed",
      "items": [
       {
        "id": "wed-B-4-0",
        "label": "1 HiPro strawberry Greek yogurt cup (200 g)",
        "kcal": 127,
        "protein": 18.0,
        "carbs": 12.0,
        "fat": 0.9
       }
      ]
     }
    ]
   }
  },
  {
   "day": "Thursday",
   "training": "Rest day",
   "shape": "Two meals plus supper",
   "options": {
    "A": [
     {
      "time": "11:00",
      "name": "Brunch",
      "note": "Eggs with turkey on toast, salad, yogurt cup to finish",
      "items": [
       {
        "id": "thu-A-0-0",
        "label": "3 large eggs",
        "kcal": 254,
        "protein": 25.0,
        "carbs": 0.0,
        "fat": 17.0
       },
       {
        "id": "thu-A-0-1",
        "label": "2 slices Domty high protein toast",
        "kcal": 170,
        "protein": 9.2,
        "carbs": 28.4,
        "fat": 2.2
       },
       {
        "id": "thu-A-0-2",
        "label": "40 g smoked turkey slices",
        "kcal": 46,
        "protein": 9.2,
        "carbs": 0.5,
        "fat": 0.8
       },
       {
        "id": "thu-A-0-3",
        "label": "150 g salad veg (cucumber, tomato, leaves)",
        "kcal": 20,
        "protein": 1.4,
        "carbs": 2.8,
        "fat": 0.4
       },
       {
        "id": "thu-A-0-4",
        "label": "1 HiPro strawberry Greek yogurt cup (200 g)",
        "kcal": 127,
        "protein": 18.0,
        "carbs": 12.0,
        "fat": 0.9
       }
      ]
     },
     {
      "time": "19:30",
      "name": "Dinner",
      "note": "Pan-seared fillet, rice, veg in the oil",
      "items": [
       {
        "id": "thu-A-1-0",
        "label": "225 g beef fillet (cooked)",
        "kcal": 423,
        "protein": 65.5,
        "carbs": 0.0,
        "fat": 18.0
       },
       {
        "id": "thu-A-1-1",
        "label": "200 g basmati rice (cooked)",
        "kcal": 234,
        "protein": 5.6,
        "carbs": 53.0,
        "fat": 1.4
       },
       {
        "id": "thu-A-1-2",
        "label": "200 g steamed mixed veg",
        "kcal": 84,
        "protein": 6.6,
        "carbs": 13.2,
        "fat": 1.0
       },
       {
        "id": "thu-A-1-3",
        "label": "5 teaspoons olive oil",
        "kcal": 205,
        "protein": 0.0,
        "carbs": 0.0,
        "fat": 22.8
       }
      ]
     },
     {
      "time": "22:30",
      "name": "Supper",
      "note": "Cottage cheese on toast, crisps",
      "items": [
       {
        "id": "thu-A-2-0",
        "label": "300 g cottage cheese",
        "kcal": 204,
        "protein": 31.8,
        "carbs": 9.9,
        "fat": 4.5
       },
       {
        "id": "thu-A-2-1",
        "label": "2 slices Domty high protein toast",
        "kcal": 170,
        "protein": 9.2,
        "carbs": 28.4,
        "fat": 2.2
       },
       {
        "id": "thu-A-2-2",
        "label": "10 g Balance protein crisps",
        "kcal": 40,
        "protein": 2.3,
        "carbs": 5.4,
        "fat": 1.3
       }
      ]
     }
    ],
    "B": [
     {
      "time": "11:00",
      "name": "Brunch",
      "note": "Egg with turkey and cheddar on toast, salad, yogurt cup to finish",
      "items": [
       {
        "id": "thu-B-0-0",
        "label": "1 large egg",
        "kcal": 85,
        "protein": 8.3,
        "carbs": 0.0,
        "fat": 5.7
       },
       {
        "id": "thu-B-0-1",
        "label": "2 slices Domty high protein toast",
        "kcal": 170,
        "protein": 9.2,
        "carbs": 28.4,
        "fat": 2.2
       },
       {
        "id": "thu-B-0-2",
        "label": "10 g cheddar slices",
        "kcal": 30,
        "protein": 1.8,
        "carbs": 0.5,
        "fat": 2.3
       },
       {
        "id": "thu-B-0-3",
        "label": "50 g smoked turkey slices",
        "kcal": 57,
        "protein": 11.5,
        "carbs": 0.6,
        "fat": 0.9
       },
       {
        "id": "thu-B-0-4",
        "label": "100 g salad veg (cucumber, tomato, leaves)",
        "kcal": 13,
        "protein": 0.9,
        "carbs": 1.9,
        "fat": 0.3
       },
       {
        "id": "thu-B-0-5",
        "label": "1 HiPro strawberry Greek yogurt cup (200 g)",
        "kcal": 127,
        "protein": 18.0,
        "carbs": 12.0,
        "fat": 0.9
       }
      ]
     },
     {
      "time": "19:00",
      "name": "Dinner, before the drinks",
      "note": "Grilled chicken, veg. Eat before the first can",
      "items": [
       {
        "id": "thu-B-1-0",
        "label": "300 g chicken breast (cooked)",
        "kcal": 444,
        "protein": 96.0,
        "carbs": 0.0,
        "fat": 6.6
       },
       {
        "id": "thu-B-1-1",
        "label": "100 g steamed mixed veg",
        "kcal": 42,
        "protein": 3.3,
        "carbs": 6.6,
        "fat": 0.5
       }
      ]
     },
     {
      "time": "After drinks",
      "name": "Supper",
      "note": "Cottage cheese and turkey on toast, then bed",
      "items": [
       {
        "id": "thu-B-2-0",
        "label": "50 g cottage cheese",
        "kcal": 34,
        "protein": 5.3,
        "carbs": 1.6,
        "fat": 0.8
       },
       {
        "id": "thu-B-2-1",
        "label": "2 slices Domty high protein toast",
        "kcal": 170,
        "protein": 9.2,
        "carbs": 28.4,
        "fat": 2.2
       },
       {
        "id": "thu-B-2-2",
        "label": "50 g smoked turkey slices",
        "kcal": 57,
        "protein": 11.5,
        "carbs": 0.6,
        "fat": 0.9
       }
      ]
     }
    ]
   }
  },
  {
   "day": "Friday",
   "training": "Padel, evening",
   "shape": "Light dinner, supper",
   "options": {
    "A": [
     {
      "time": "08:30",
      "name": "Breakfast",
      "note": "Boiled eggs, cottage cheese on toast, tomato and cucumber",
      "items": [
       {
        "id": "fri-A-0-0",
        "label": "150 g cottage cheese",
        "kcal": 102,
        "protein": 15.9,
        "carbs": 4.9,
        "fat": 2.2
       },
       {
        "id": "fri-A-0-1",
        "label": "2 slices Domty high protein toast",
        "kcal": 170,
        "protein": 9.2,
        "carbs": 28.4,
        "fat": 2.2
       },
       {
        "id": "fri-A-0-2",
        "label": "3 large eggs",
        "kcal": 254,
        "protein": 25.0,
        "carbs": 0.0,
        "fat": 17.0
       },
       {
        "id": "fri-A-0-3",
        "label": "100 g salad veg (cucumber, tomato, leaves)",
        "kcal": 13,
        "protein": 0.9,
        "carbs": 1.9,
        "fat": 0.3
       }
      ]
     },
     {
      "time": "13:30",
      "name": "Lunch",
      "note": "Grilled chicken, rice, veg in the oil",
      "items": [
       {
        "id": "fri-A-1-0",
        "label": "170 g chicken breast (cooked)",
        "kcal": 252,
        "protein": 54.4,
        "carbs": 0.0,
        "fat": 3.7
       },
       {
        "id": "fri-A-1-1",
        "label": "170 g basmati rice (cooked)",
        "kcal": 199,
        "protein": 4.8,
        "carbs": 45.0,
        "fat": 1.2
       },
       {
        "id": "fri-A-1-2",
        "label": "200 g steamed mixed veg",
        "kcal": 84,
        "protein": 6.6,
        "carbs": 13.2,
        "fat": 1.0
       },
       {
        "id": "fri-A-1-3",
        "label": "6 teaspoons olive oil",
        "kcal": 246,
        "protein": 0.0,
        "carbs": 0.0,
        "fat": 27.4
       }
      ]
     },
     {
      "time": "21:00",
      "name": "Dinner, after padel",
      "note": "Tuna on toast, big salad with oil and lemon dressing",
      "items": [
       {
        "id": "fri-A-2-0",
        "label": "150 g tuna in water (drained)",
        "kcal": 164,
        "protein": 37.3,
        "carbs": 0.0,
        "fat": 1.5
       },
       {
        "id": "fri-A-2-1",
        "label": "2 slices Domty high protein toast",
        "kcal": 170,
        "protein": 9.2,
        "carbs": 28.4,
        "fat": 2.2
       },
       {
        "id": "fri-A-2-2",
        "label": "200 g salad veg (cucumber, tomato, leaves)",
        "kcal": 26,
        "protein": 1.8,
        "carbs": 3.7,
        "fat": 0.5
       },
       {
        "id": "fri-A-2-3",
        "label": "3 teaspoons olive oil",
        "kcal": 123,
        "protein": 0.0,
        "carbs": 0.0,
        "fat": 13.7
       }
      ]
     },
     {
      "time": "23:00",
      "name": "Supper",
      "note": "Yogurt cup, apple",
      "items": [
       {
        "id": "fri-A-3-0",
        "label": "1 HiPro strawberry Greek yogurt cup (200 g)",
        "kcal": 127,
        "protein": 18.0,
        "carbs": 12.0,
        "fat": 0.9
       },
       {
        "id": "fri-A-3-1",
        "label": "150 g apple",
        "kcal": 76,
        "protein": 0.9,
        "carbs": 17.4,
        "fat": 0.8
       }
      ]
     }
    ],
    "B": [
     {
      "time": "08:30",
      "name": "Breakfast",
      "note": "Boiled egg, cottage cheese on toast, tomato and cucumber",
      "items": [
       {
        "id": "fri-B-0-0",
        "label": "90 g cottage cheese",
        "kcal": 61,
        "protein": 9.5,
        "carbs": 3.0,
        "fat": 1.4
       },
       {
        "id": "fri-B-0-1",
        "label": "2 slices Domty high protein toast",
        "kcal": 170,
        "protein": 9.2,
        "carbs": 28.4,
        "fat": 2.2
       },
       {
        "id": "fri-B-0-2",
        "label": "1 large egg",
        "kcal": 85,
        "protein": 8.3,
        "carbs": 0.0,
        "fat": 5.7
       },
       {
        "id": "fri-B-0-3",
        "label": "50 g salad veg (cucumber, tomato, leaves)",
        "kcal": 6,
        "protein": 0.5,
        "carbs": 0.9,
        "fat": 0.1
       }
      ]
     },
     {
      "time": "13:30",
      "name": "Lunch",
      "note": "Grilled chicken, veg",
      "items": [
       {
        "id": "fri-B-1-0",
        "label": "210 g chicken breast (cooked)",
        "kcal": 311,
        "protein": 67.2,
        "carbs": 0.0,
        "fat": 4.6
       },
       {
        "id": "fri-B-1-1",
        "label": "100 g steamed mixed veg",
        "kcal": 42,
        "protein": 3.3,
        "carbs": 6.6,
        "fat": 0.5
       }
      ]
     },
     {
      "time": "21:00",
      "name": "Dinner, before the drinks",
      "note": "Tuna on toast with salad. Eat before the first can",
      "items": [
       {
        "id": "fri-B-2-0",
        "label": "200 g tuna in water (drained)",
        "kcal": 218,
        "protein": 49.8,
        "carbs": 0.0,
        "fat": 2.0
       },
       {
        "id": "fri-B-2-1",
        "label": "2 slices Domty high protein toast",
        "kcal": 170,
        "protein": 9.2,
        "carbs": 28.4,
        "fat": 2.2
       },
       {
        "id": "fri-B-2-2",
        "label": "50 g salad veg (cucumber, tomato, leaves)",
        "kcal": 6,
        "protein": 0.5,
        "carbs": 0.9,
        "fat": 0.1
       }
      ]
     },
     {
      "time": "After drinks",
      "name": "Supper",
      "note": "Yogurt cup and turkey, then bed",
      "items": [
       {
        "id": "fri-B-3-0",
        "label": "1 HiPro strawberry Greek yogurt cup (200 g)",
        "kcal": 127,
        "protein": 18.0,
        "carbs": 12.0,
        "fat": 0.9
       },
       {
        "id": "fri-B-3-1",
        "label": "20 g smoked turkey slices",
        "kcal": 23,
        "protein": 4.6,
        "carbs": 0.2,
        "fat": 0.4
       }
      ]
     }
    ]
   }
  },
  {
   "day": "Saturday",
   "training": "Gym, evening",
   "shape": "Heavy dinner, no supper",
   "options": {
    "A": [
     {
      "time": "10:00",
      "name": "Breakfast",
      "note": "Eggs with turkey and cheddar on toast, salad on the side",
      "items": [
       {
        "id": "sat-A-0-0",
        "label": "3 large eggs",
        "kcal": 254,
        "protein": 25.0,
        "carbs": 0.0,
        "fat": 17.0
       },
       {
        "id": "sat-A-0-1",
        "label": "10 g smoked turkey slices",
        "kcal": 11,
        "protein": 2.3,
        "carbs": 0.1,
        "fat": 0.2
       },
       {
        "id": "sat-A-0-2",
        "label": "20 g cheddar slices",
        "kcal": 59,
        "protein": 3.6,
        "carbs": 1.0,
        "fat": 4.6
       },
       {
        "id": "sat-A-0-3",
        "label": "2 slices Domty high protein toast",
        "kcal": 170,
        "protein": 9.2,
        "carbs": 28.4,
        "fat": 2.2
       },
       {
        "id": "sat-A-0-4",
        "label": "100 g salad veg (cucumber, tomato, leaves)",
        "kcal": 13,
        "protein": 0.9,
        "carbs": 1.9,
        "fat": 0.3
       }
      ]
     },
     {
      "time": "14:30",
      "name": "Lunch",
      "note": "Tuna on toast, veg with the oil over it",
      "items": [
       {
        "id": "sat-A-1-0",
        "label": "120 g tuna in water (drained)",
        "kcal": 131,
        "protein": 29.9,
        "carbs": 0.0,
        "fat": 1.2
       },
       {
        "id": "sat-A-1-1",
        "label": "2 slices Domty high protein toast",
        "kcal": 170,
        "protein": 9.2,
        "carbs": 28.4,
        "fat": 2.2
       },
       {
        "id": "sat-A-1-2",
        "label": "150 g steamed mixed veg",
        "kcal": 63,
        "protein": 4.9,
        "carbs": 9.9,
        "fat": 0.8
       },
       {
        "id": "sat-A-1-3",
        "label": "2 teaspoons olive oil",
        "kcal": 82,
        "protein": 0.0,
        "carbs": 0.0,
        "fat": 9.1
       }
      ]
     },
     {
      "time": "20:30",
      "name": "After the gym",
      "note": "Shake with water, honey stirred in",
      "items": [
       {
        "id": "sat-A-2-0",
        "label": "1 scoop whey protein (33 g) in water",
        "kcal": 110,
        "protein": 26.0,
        "carbs": 1.0,
        "fat": 0.5
       },
       {
        "id": "sat-A-2-1",
        "label": "1 teaspoon honey",
        "kcal": 20,
        "protein": 0.0,
        "carbs": 5.3,
        "fat": 0.0
       }
      ]
     },
     {
      "time": "21:30",
      "name": "Dinner",
      "note": "Mince with onion, garlic and spices, thin fries from the air fryer with no oil, veg in the oil",
      "items": [
       {
        "id": "sat-A-3-0",
        "label": "240 g extra lean minced beef (cooked)",
        "kcal": 329,
        "protein": 59.3,
        "carbs": 0.0,
        "fat": 10.1
       },
       {
        "id": "sat-A-3-1",
        "label": "150 g Farm Frites thin fries (air-fried, no oil)",
        "kcal": 284,
        "protein": 4.8,
        "carbs": 52.9,
        "fat": 7.4
       },
       {
        "id": "sat-A-3-2",
        "label": "250 g steamed mixed veg",
        "kcal": 105,
        "protein": 8.2,
        "carbs": 16.5,
        "fat": 1.2
       },
       {
        "id": "sat-A-3-3",
        "label": "4 teaspoons olive oil",
        "kcal": 164,
        "protein": 0.0,
        "carbs": 0.0,
        "fat": 18.2
       }
      ]
     }
    ],
    "B": [
     {
      "time": "10:00",
      "name": "Breakfast",
      "note": "Egg and turkey with salad, no wrap today",
      "items": [
       {
        "id": "sat-B-0-0",
        "label": "1 large egg",
        "kcal": 85,
        "protein": 8.3,
        "carbs": 0.0,
        "fat": 5.7
       },
       {
        "id": "sat-B-0-1",
        "label": "100 g smoked turkey slices",
        "kcal": 114,
        "protein": 23.0,
        "carbs": 1.2,
        "fat": 1.9
       },
       {
        "id": "sat-B-0-2",
        "label": "50 g salad veg (cucumber, tomato, leaves)",
        "kcal": 6,
        "protein": 0.5,
        "carbs": 0.9,
        "fat": 0.1
       }
      ]
     },
     {
      "time": "14:30",
      "name": "Lunch",
      "note": "Tuna on toast, veg on the side",
      "items": [
       {
        "id": "sat-B-1-0",
        "label": "190 g tuna in water (drained)",
        "kcal": 207,
        "protein": 47.3,
        "carbs": 0.0,
        "fat": 1.9
       },
       {
        "id": "sat-B-1-1",
        "label": "2 slices Domty high protein toast",
        "kcal": 170,
        "protein": 9.2,
        "carbs": 28.4,
        "fat": 2.2
       },
       {
        "id": "sat-B-1-2",
        "label": "100 g steamed mixed veg",
        "kcal": 42,
        "protein": 3.3,
        "carbs": 6.6,
        "fat": 0.5
       }
      ]
     },
     {
      "time": "20:30",
      "name": "After the gym",
      "note": "Shake with water",
      "items": [
       {
        "id": "sat-B-2-0",
        "label": "1 scoop whey protein (33 g) in water",
        "kcal": 110,
        "protein": 26.0,
        "carbs": 1.0,
        "fat": 0.5
       }
      ]
     },
     {
      "time": "21:30",
      "name": "Dinner, before the drinks",
      "note": "Mince with onion, garlic and spices, veg. Eat before the first can",
      "items": [
       {
        "id": "sat-B-3-0",
        "label": "170 g extra lean minced beef (cooked)",
        "kcal": 233,
        "protein": 42.0,
        "carbs": 0.0,
        "fat": 7.1
       },
       {
        "id": "sat-B-3-1",
        "label": "100 g steamed mixed veg",
        "kcal": 42,
        "protein": 3.3,
        "carbs": 6.6,
        "fat": 0.5
       }
      ]
     },
     {
      "time": "After drinks",
      "name": "Supper",
      "note": "Cottage cheese on toast, then bed",
      "items": [
       {
        "id": "sat-B-4-0",
        "label": "60 g cottage cheese",
        "kcal": 41,
        "protein": 6.4,
        "carbs": 2.0,
        "fat": 0.9
       },
       {
        "id": "sat-B-4-1",
        "label": "2 slices Domty high protein toast",
        "kcal": 170,
        "protein": 9.2,
        "carbs": 28.4,
        "fat": 2.2
       }
      ]
     }
    ]
   }
  },
  {
   "day": "Sunday",
   "training": "Rest day",
   "shape": "Two meals plus supper",
   "options": {
    "A": [
     {
      "time": "11:00",
      "name": "Brunch",
      "note": "Big omelette with cheddar and turkey, toast, salad in the oil",
      "items": [
       {
        "id": "sun-A-0-0",
        "label": "4 large eggs",
        "kcal": 338,
        "protein": 33.3,
        "carbs": 0.0,
        "fat": 22.7
       },
       {
        "id": "sun-A-0-1",
        "label": "2 slices Domty high protein toast",
        "kcal": 170,
        "protein": 9.2,
        "carbs": 28.4,
        "fat": 2.2
       },
       {
        "id": "sun-A-0-2",
        "label": "40 g cheddar slices",
        "kcal": 119,
        "protein": 7.1,
        "carbs": 2.0,
        "fat": 9.2
       },
       {
        "id": "sun-A-0-3",
        "label": "40 g smoked turkey slices",
        "kcal": 46,
        "protein": 9.2,
        "carbs": 0.5,
        "fat": 0.8
       },
       {
        "id": "sun-A-0-4",
        "label": "150 g salad veg (cucumber, tomato, leaves)",
        "kcal": 20,
        "protein": 1.4,
        "carbs": 2.8,
        "fat": 0.4
       },
       {
        "id": "sun-A-0-5",
        "label": "3 teaspoons olive oil",
        "kcal": 123,
        "protein": 0.0,
        "carbs": 0.0,
        "fat": 13.7
       }
      ]
     },
     {
      "time": "18:30",
      "name": "Dinner",
      "note": "Grilled chicken, rice, veg in the oil",
      "items": [
       {
        "id": "sun-A-1-0",
        "label": "190 g chicken breast (cooked)",
        "kcal": 281,
        "protein": 60.8,
        "carbs": 0.0,
        "fat": 4.2
       },
       {
        "id": "sun-A-1-1",
        "label": "190 g basmati rice (cooked)",
        "kcal": 222,
        "protein": 5.3,
        "carbs": 50.3,
        "fat": 1.3
       },
       {
        "id": "sun-A-1-2",
        "label": "200 g steamed mixed veg",
        "kcal": 84,
        "protein": 6.6,
        "carbs": 13.2,
        "fat": 1.0
       },
       {
        "id": "sun-A-1-3",
        "label": "2 teaspoons olive oil",
        "kcal": 82,
        "protein": 0.0,
        "carbs": 0.0,
        "fat": 9.1
       }
      ]
     },
     {
      "time": "22:00",
      "name": "Supper",
      "note": "Yogurt cup, cottage cheese and turkey on toast, apple",
      "items": [
       {
        "id": "sun-A-2-0",
        "label": "1 HiPro strawberry Greek yogurt cup (200 g)",
        "kcal": 127,
        "protein": 18.0,
        "carbs": 12.0,
        "fat": 0.9
       },
       {
        "id": "sun-A-2-1",
        "label": "150 g cottage cheese",
        "kcal": 102,
        "protein": 15.9,
        "carbs": 4.9,
        "fat": 2.2
       },
       {
        "id": "sun-A-2-2",
        "label": "2 slices Domty high protein toast",
        "kcal": 170,
        "protein": 9.2,
        "carbs": 28.4,
        "fat": 2.2
       },
       {
        "id": "sun-A-2-3",
        "label": "20 g smoked turkey slices",
        "kcal": 23,
        "protein": 4.6,
        "carbs": 0.2,
        "fat": 0.4
       },
       {
        "id": "sun-A-2-4",
        "label": "100 g apple",
        "kcal": 51,
        "protein": 0.6,
        "carbs": 11.6,
        "fat": 0.5
       }
      ]
     }
    ],
    "B": [
     {
      "time": "11:00",
      "name": "Brunch",
      "note": "One-egg omelette with turkey, toast, salad",
      "items": [
       {
        "id": "sun-B-0-0",
        "label": "1 large egg",
        "kcal": 85,
        "protein": 8.3,
        "carbs": 0.0,
        "fat": 5.7
       },
       {
        "id": "sun-B-0-1",
        "label": "2 slices Domty high protein toast",
        "kcal": 170,
        "protein": 9.2,
        "carbs": 28.4,
        "fat": 2.2
       },
       {
        "id": "sun-B-0-2",
        "label": "70 g smoked turkey slices",
        "kcal": 80,
        "protein": 16.1,
        "carbs": 0.8,
        "fat": 1.3
       },
       {
        "id": "sun-B-0-3",
        "label": "50 g salad veg (cucumber, tomato, leaves)",
        "kcal": 6,
        "protein": 0.5,
        "carbs": 0.9,
        "fat": 0.1
       }
      ]
     },
     {
      "time": "18:30",
      "name": "Dinner, before the drinks",
      "note": "Grilled chicken, veg. Eat before the first can",
      "items": [
       {
        "id": "sun-B-1-0",
        "label": "300 g chicken breast (cooked)",
        "kcal": 444,
        "protein": 96.0,
        "carbs": 0.0,
        "fat": 6.6
       },
       {
        "id": "sun-B-1-1",
        "label": "100 g steamed mixed veg",
        "kcal": 42,
        "protein": 3.3,
        "carbs": 6.6,
        "fat": 0.5
       }
      ]
     },
     {
      "time": "After drinks",
      "name": "Supper",
      "note": "Yogurt cup, cottage cheese and turkey on toast, then bed",
      "items": [
       {
        "id": "sun-B-2-0",
        "label": "1 HiPro strawberry Greek yogurt cup (200 g)",
        "kcal": 127,
        "protein": 18.0,
        "carbs": 12.0,
        "fat": 0.9
       },
       {
        "id": "sun-B-2-1",
        "label": "50 g cottage cheese",
        "kcal": 34,
        "protein": 5.3,
        "carbs": 1.6,
        "fat": 0.8
       },
       {
        "id": "sun-B-2-2",
        "label": "2 slices Domty high protein toast",
        "kcal": 170,
        "protein": 9.2,
        "carbs": 28.4,
        "fat": 2.2
       },
       {
        "id": "sun-B-2-3",
        "label": "40 g smoked turkey slices",
        "kcal": 46,
        "protein": 9.2,
        "carbs": 0.5,
        "fat": 0.8
       }
      ]
     }
    ]
   }
  }
 ]
};
